// 由 `npm run tui:gen` 生成，别手改。
//
// 真源是 src/lib/tui/surface.ts —— 改那里，然后重新生成。
// 手改这个文件的话，改动会在下一次生成时被覆盖，
// 而在那之前它会让 tests/tui-parity.test.ts 报一个看不懂的差异。

package surface

// Surfaces 是站里每一个「面」。顺序就是终端最左那一竖里的显示顺序 ——
// 排序是产品决定，所以它跟着真源走，不在 Go 这边重排。
var Surfaces = []Surface{
	{
		Key:            "chat.archive",
		Label:          "按天回看",
		Board:          "chat",
		Web:            "/archive",
		Screen:         "chat/archive",
		Why:            "",
		API:            []string{"GET /api/v1/groups", "GET /api/v1/archive", "GET /api/v1/groups/{conv_id}/messages"},
		Scopes:         []string{"groups:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "chat.live",
		Label:          "群聊",
		Board:          "chat",
		Web:            "",
		Screen:         "chat/live",
		Why:            "",
		API:            []string{"GET /api/v1/groups", "GET /api/v1/groups/{conv_id}/messages", "POST /api/v1/groups/{conv_id}/messages", "GET /api/v1/groups/{conv_id}/members"},
		Scopes:         []string{"groups:read"},
		OptionalScopes: []string{"groups:send"},
		AdminSection:   "",
	},
	{
		Key:            "chat.search",
		Label:          "检索",
		Board:          "chat",
		Web:            "/search",
		Screen:         "chat/search",
		Why:            "",
		API:            []string{"GET /api/v1/search"},
		Scopes:         []string{"groups:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "chat.links",
		Label:          "资源库",
		Board:          "chat",
		Web:            "/links",
		Screen:         "chat/links",
		Why:            "",
		API:            []string{"GET /api/v1/links", "POST /api/v1/links/{id}/vote", "POST /api/v1/links/{id}/save"},
		Scopes:         []string{"groups:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "chat.radar",
		Label:          "关键词雷达",
		Board:          "chat",
		Web:            "/radar",
		Screen:         "chat/radar",
		Why:            "",
		API:            []string{"GET /api/v1/radar", "POST /api/v1/radar", "DELETE /api/v1/radar/{id}"},
		Scopes:         []string{"groups:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "chat.stats",
		Label:          "群统计",
		Board:          "chat",
		Web:            "",
		Screen:         "chat/stats",
		Why:            "",
		API:            []string{"GET /api/v1/groups/{conv_id}/stats"},
		Scopes:         []string{"groups:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "chat.announcement",
		Label:          "群公告",
		Board:          "chat",
		Web:            "",
		Screen:         "chat/announcement",
		Why:            "",
		API:            []string{"GET /api/v1/groups/{conv_id}/announcement", "POST /api/v1/groups/{conv_id}/announcement"},
		Scopes:         []string{"groups:read"},
		OptionalScopes: []string{"groups:send"},
		AdminSection:   "",
	},
	{
		Key:            "forum.index",
		Label:          "论坛",
		Board:          "forum",
		Web:            "/forum",
		Screen:         "forum/index",
		Why:            "",
		API:            []string{"GET /api/v1/forum/boards", "GET /api/v1/posts"},
		Scopes:         []string{"forum:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "forum.board",
		Label:          "版块",
		Board:          "forum",
		Web:            "/forum/[board]",
		Screen:         "forum/board",
		Why:            "",
		API:            []string{"GET /api/v1/posts"},
		Scopes:         []string{"forum:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "forum.post",
		Label:          "帖子正文",
		Board:          "forum",
		Web:            "/forum/p/[id]",
		Screen:         "forum/post",
		Why:            "",
		API:            []string{"GET /api/v1/posts/{id}", "POST /api/v1/posts/{id}/replies", "POST /api/v1/posts/{id}/react", "POST /api/v1/posts/{id}/vote", "POST /api/v1/posts/{id}/accept", "POST /api/v1/posts/{id}/report", "POST /api/v1/posts/{id}/tip", "POST /api/v1/posts/{id}/bookmark"},
		Scopes:         []string{"forum:read"},
		OptionalScopes: []string{"forum:write", "economy:write", "me:write"},
		AdminSection:   "",
	},
	{
		Key:            "forum.new",
		Label:          "发帖",
		Board:          "forum",
		Web:            "/forum/new",
		Screen:         "forum/new",
		Why:            "",
		API:            []string{"GET /api/v1/forum/boards", "POST /api/v1/posts", "POST /api/v1/me/drafts"},
		Scopes:         []string{"forum:write"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "forum.edit",
		Label:          "编辑帖子",
		Board:          "forum",
		Web:            "/forum/p/[id]/edit",
		Screen:         "forum/edit",
		Why:            "",
		API:            []string{"GET /api/v1/posts/{id}", "PATCH /api/v1/posts/{id}"},
		Scopes:         []string{"forum:write"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "forum.history",
		Label:          "编辑历史",
		Board:          "forum",
		Web:            "/forum/p/[id]/history",
		Screen:         "forum/history",
		Why:            "",
		API:            []string{"GET /api/v1/posts/{id}/history"},
		Scopes:         []string{"forum:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "forum.search",
		Label:          "论坛搜索",
		Board:          "forum",
		Web:            "/forum/search",
		Screen:         "forum/search",
		Why:            "",
		API:            []string{"GET /api/v1/forum/search"},
		Scopes:         []string{"forum:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "forum.deep",
		Label:          "深潜",
		Board:          "forum",
		Web:            "/forum/deep",
		Screen:         "forum/deep",
		Why:            "",
		API:            []string{"GET /api/v1/forum/deep"},
		Scopes:         []string{"forum:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "forum.convert",
		Label:          "群消息转帖",
		Board:          "forum",
		Web:            "/forum/convert",
		Screen:         "forum/convert",
		Why:            "",
		API:            []string{"GET /api/v1/groups/{conv_id}/messages", "POST /api/v1/forum/convert"},
		Scopes:         []string{"forum:write", "groups:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.home",
		Label:          "首页",
		Board:          "community",
		Web:            "/",
		Screen:         "community/home",
		Why:            "",
		API:            []string{"GET /api/v1/home"},
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.members",
		Label:          "成员",
		Board:          "community",
		Web:            "/members",
		Screen:         "community/members",
		Why:            "",
		API:            []string{"GET /api/v1/members"},
		Scopes:         []string{"community:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.person",
		Label:          "成员主页",
		Board:          "community",
		Web:            "/members/[wxId]",
		Screen:         "community/person",
		Why:            "",
		API:            []string{"GET /api/v1/members/{wx_id}", "POST /api/v1/me/following"},
		Scopes:         []string{"community:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "community.person-by-id",
		Label:          "按账号 id 找人",
		Board:          "community",
		Web:            "/members/by/[userId]",
		Screen:         "",
		Why:            "网页上它只是一个 302 跳板；终端里跳转在客户端内部完成，没有对应物",
		API:            []string{"GET /api/v1/members/{wx_id}"},
		Scopes:         []string{"community:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.leaderboard",
		Label:          "排行榜",
		Board:          "community",
		Web:            "/leaderboard",
		Screen:         "community/leaderboard",
		Why:            "",
		API:            []string{"GET /api/v1/leaderboard"},
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.projects",
		Label:          "项目目录",
		Board:          "community",
		Web:            "/projects",
		Screen:         "community/projects",
		Why:            "",
		API:            []string{"GET /api/v1/projects", "POST /api/v1/projects"},
		Scopes:         []string{"community:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "community.repo",
		Label:          "项目详情",
		Board:          "community",
		Web:            "/projects/[owner]/[repo]",
		Screen:         "community/repo",
		Why:            "",
		API:            []string{"GET /api/v1/projects/{owner}/{repo}"},
		Scopes:         []string{"community:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.activities",
		Label:          "活动",
		Board:          "community",
		Web:            "/activities",
		Screen:         "community/activities",
		Why:            "",
		API:            []string{"GET /api/v1/activities", "GET /api/v1/activities/{id}", "POST /api/v1/activities/{id}/apply"},
		Scopes:         []string{"community:read"},
		OptionalScopes: []string{"activities:write"},
		AdminSection:   "",
	},
	{
		Key:            "community.activity",
		Label:          "活动详情",
		Board:          "community",
		Web:            "",
		Screen:         "community/activity",
		Why:            "",
		API:            []string{"GET /api/v1/activities/{id}", "POST /api/v1/activities/{id}/apply"},
		Scopes:         []string{"community:read"},
		OptionalScopes: []string{"activities:write"},
		AdminSection:   "",
	},
	{
		Key:            "community.shop",
		Label:          "商店",
		Board:          "community",
		Web:            "/shop",
		Screen:         "community/shop",
		Why:            "",
		API:            []string{"GET /api/v1/shop", "POST /api/v1/shop/{id}/buy"},
		Scopes:         []string{"community:read"},
		OptionalScopes: []string{"economy:write"},
		AdminSection:   "",
	},
	{
		Key:            "community.welcome",
		Label:          "新人引导",
		Board:          "community",
		Web:            "/welcome",
		Screen:         "community/welcome",
		Why:            "",
		API:            []string{"GET /api/v1/welcome"},
		Scopes:         []string{"me:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.onboarding",
		Label:          "入站设置",
		Board:          "community",
		Web:            "/onboarding",
		Screen:         "community/onboarding",
		Why:            "",
		API:            []string{"GET /api/v1/welcome", "POST /api/v1/me/profile"},
		Scopes:         []string{"me:write"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.join",
		Label:          "申请加入",
		Board:          "community",
		Web:            "/join",
		Screen:         "",
		Why:            "给没有账号的人用的，而终端的第一步就是登录 —— 在这里开入口等于绕开「只有群成员能登录」",
		API:            nil,
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.login",
		Label:          "登录",
		Board:          "community",
		Web:            "/login",
		Screen:         "",
		Why:            "终端登录走设备码（见 TUI.md 第四节）；密码和 passkey 都要浏览器，终端里没有认证器",
		API:            []string{"POST /api/v1/auth/device/start", "POST /api/v1/auth/device/poll"},
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "community.device-link",
		Label:          "确认终端登录",
		Board:          "community",
		Web:            "/link",
		Screen:         "",
		Why:            "设备码流程的浏览器那一半：终端里也能确认的话，就成了终端自己批准自己，中间那道人的判断整个消失",
		API:            nil,
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "me.home",
		Label:          "我的",
		Board:          "me",
		Web:            "/me",
		Screen:         "me/home",
		Why:            "",
		API:            []string{"GET /api/v1/me"},
		Scopes:         []string{"me:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "me.profile",
		Label:          "编辑资料",
		Board:          "me",
		Web:            "/me/profile",
		Screen:         "me/profile",
		Why:            "",
		API:            []string{"GET /api/v1/me", "POST /api/v1/me/profile"},
		Scopes:         []string{"me:write"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "me.points",
		Label:          "积分与打卡",
		Board:          "me",
		Web:            "/me/points",
		Screen:         "me/points",
		Why:            "",
		API:            []string{"GET /api/v1/me/points", "POST /api/v1/me/checkin", "POST /api/v1/me/makeup"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write", "economy:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.titles",
		Label:          "称号",
		Board:          "me",
		Web:            "",
		Screen:         "me/titles",
		Why:            "",
		API:            []string{"GET /api/v1/me/titles", "POST /api/v1/me/titles/equip"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.bookmarks",
		Label:          "收藏夹",
		Board:          "me",
		Web:            "/me/bookmarks",
		Screen:         "me/bookmarks",
		Why:            "",
		API:            []string{"GET /api/v1/me/bookmarks", "POST /api/v1/posts/{id}/bookmark"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.drafts",
		Label:          "草稿箱",
		Board:          "me",
		Web:            "/me/drafts",
		Screen:         "me/drafts",
		Why:            "",
		API:            []string{"GET /api/v1/me/drafts", "POST /api/v1/me/drafts", "DELETE /api/v1/me/drafts/{id}"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.following",
		Label:          "关注",
		Board:          "me",
		Web:            "/me/following",
		Screen:         "me/following",
		Why:            "",
		API:            []string{"GET /api/v1/me/following", "POST /api/v1/me/following"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.notifications",
		Label:          "通知",
		Board:          "me",
		Web:            "/notifications",
		Screen:         "me/notifications",
		Why:            "",
		API:            []string{"GET /api/v1/me/notifications", "POST /api/v1/me/notifications/read", "GET /api/v1/me/notifications/stream"},
		Scopes:         []string{"notifications:read"},
		OptionalScopes: []string{"notifications:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.notification-prefs",
		Label:          "通知设置",
		Board:          "me",
		Web:            "/me/notifications",
		Screen:         "me/notification-prefs",
		Why:            "",
		API:            []string{"GET /api/v1/me/notifications/prefs", "POST /api/v1/me/notifications/prefs"},
		Scopes:         []string{"notifications:write"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "me.privacy",
		Label:          "隐私",
		Board:          "me",
		Web:            "/me/privacy",
		Screen:         "me/privacy",
		Why:            "",
		API:            []string{"GET /api/v1/me/privacy", "POST /api/v1/me/privacy"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.moderation",
		Label:          "我的处罚与申诉",
		Board:          "me",
		Web:            "/me/moderation",
		Screen:         "me/moderation",
		Why:            "",
		API:            []string{"GET /api/v1/me/moderation", "POST /api/v1/me/appeals"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.tokens",
		Label:          "开放 API",
		Board:          "me",
		Web:            "/me/api",
		Screen:         "me/tokens",
		Why:            "",
		API:            []string{"GET /api/v1/me/tokens", "POST /api/v1/me/tokens", "DELETE /api/v1/me/tokens/{id}", "GET /api/v1/docs"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.security",
		Label:          "登录与设备",
		Board:          "me",
		Web:            "/me/security",
		Screen:         "me/security",
		Why:            "",
		API:            []string{"GET /api/v1/me/sessions", "DELETE /api/v1/me/sessions/{id}"},
		Scopes:         []string{"me:read"},
		OptionalScopes: []string{"me:write"},
		AdminSection:   "",
	},
	{
		Key:            "me.export",
		Label:          "导出我的数据",
		Board:          "me",
		Web:            "/me/export",
		Screen:         "me/export",
		Why:            "",
		API:            []string{"POST /api/v1/me/export", "GET /api/v1/me/export"},
		Scopes:         []string{"me:read"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "me.update",
		Label:          "版本与自更新",
		Board:          "me",
		Web:            "",
		Screen:         "me/update",
		Why:            "",
		API:            []string{"GET /api/v1/release"},
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "me.shortlink",
		Label:          "分享短链",
		Board:          "me",
		Web:            "",
		Screen:         "",
		Why:            "网页上 /p/[code] 是一条 302 路由不是页面；终端里分享给出的是完整链接，没有中转",
		API:            nil,
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "admin.dashboard",
		Label:          "后台首页",
		Board:          "admin",
		Web:            "/admin",
		Screen:         "admin/dashboard",
		Why:            "",
		API:            []string{"GET /api/v1/admin/sections", "GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "dashboard",
	},
	{
		Key:            "admin.users",
		Label:          "用户",
		Board:          "admin",
		Web:            "/admin/users",
		Screen:         "admin/users",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "users",
	},
	{
		Key:            "admin.user",
		Label:          "用户详情",
		Board:          "admin",
		Web:            "/admin/users/[id]",
		Screen:         "admin/user",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "user",
	},
	{
		Key:            "admin.posts",
		Label:          "帖子管理",
		Board:          "admin",
		Web:            "/admin/posts",
		Screen:         "admin/posts",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "posts",
	},
	{
		Key:            "admin.reports",
		Label:          "举报",
		Board:          "admin",
		Web:            "/admin/reports",
		Screen:         "admin/reports",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "reports",
	},
	{
		Key:            "admin.appeals",
		Label:          "申诉",
		Board:          "admin",
		Web:            "/admin/appeals",
		Screen:         "admin/appeals",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "appeals",
	},
	{
		Key:            "admin.approvals",
		Label:          "审批队列",
		Board:          "admin",
		Web:            "/admin/approvals",
		Screen:         "admin/approvals",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "approvals",
	},
	{
		Key:            "admin.escalation",
		Label:          "升级处置",
		Board:          "admin",
		Web:            "/admin/escalation",
		Screen:         "admin/escalation",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "escalation",
	},
	{
		Key:            "admin.audit",
		Label:          "审计日志",
		Board:          "admin",
		Web:            "/admin/audit",
		Screen:         "admin/audit",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "audit",
	},
	{
		Key:            "admin.boards",
		Label:          "版块",
		Board:          "admin",
		Web:            "/admin/boards",
		Screen:         "admin/boards",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "boards",
	},
	{
		Key:            "admin.words",
		Label:          "敏感词",
		Board:          "admin",
		Web:            "/admin/words",
		Screen:         "admin/words",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "words",
	},
	{
		Key:            "admin.groups",
		Label:          "群与同步",
		Board:          "admin",
		Web:            "/admin/groups",
		Screen:         "admin/groups",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "groups",
	},
	{
		Key:            "admin.binds",
		Label:          "绑定队列",
		Board:          "admin",
		Web:            "/admin/binds",
		Screen:         "admin/binds",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "binds",
	},
	{
		Key:            "admin.invites",
		Label:          "邀请码",
		Board:          "admin",
		Web:            "/admin/invites",
		Screen:         "admin/invites",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "invites",
	},
	{
		Key:            "admin.roles",
		Label:          "身份组与权限矩阵",
		Board:          "admin",
		Web:            "/admin/roles",
		Screen:         "admin/roles",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "roles",
	},
	{
		Key:            "admin.settings",
		Label:          "系统设置",
		Board:          "admin",
		Web:            "/admin/settings",
		Screen:         "admin/settings",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "settings",
	},
	{
		Key:            "admin.flags",
		Label:          "功能开关",
		Board:          "admin",
		Web:            "/admin/flags",
		Screen:         "admin/flags",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "flags",
	},
	{
		Key:            "admin.modules",
		Label:          "模块",
		Board:          "admin",
		Web:            "/admin/modules",
		Screen:         "admin/modules",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "modules",
	},
	{
		Key:            "admin.points",
		Label:          "积分总览",
		Board:          "admin",
		Web:            "/admin/points",
		Screen:         "admin/points",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "points",
	},
	{
		Key:            "admin.points-ledger",
		Label:          "积分流水",
		Board:          "admin",
		Web:            "/admin/points/ledger",
		Screen:         "admin/points-ledger",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "points-ledger",
	},
	{
		Key:            "admin.points-levels",
		Label:          "等级",
		Board:          "admin",
		Web:            "/admin/points/levels",
		Screen:         "admin/points-levels",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "points-levels",
	},
	{
		Key:            "admin.shop",
		Label:          "商店管理",
		Board:          "admin",
		Web:            "/admin/shop",
		Screen:         "admin/shop",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "shop",
	},
	{
		Key:            "admin.activities",
		Label:          "活动管理",
		Board:          "admin",
		Web:            "/admin/activities",
		Screen:         "admin/activities",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "activities",
	},
	{
		Key:            "admin.broadcast",
		Label:          "群发",
		Board:          "admin",
		Web:            "/admin/broadcast",
		Screen:         "admin/broadcast",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all", "groups:send"},
		OptionalScopes: nil,
		AdminSection:   "broadcast",
	},
	{
		Key:            "admin.community",
		Label:          "社区健康",
		Board:          "admin",
		Web:            "/admin/community",
		Screen:         "admin/community",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "community",
	},
	{
		Key:            "admin.health",
		Label:          "健康检查",
		Board:          "admin",
		Web:            "/admin/health",
		Screen:         "admin/health",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "health",
	},
	{
		Key:            "admin.storage",
		Label:          "存储",
		Board:          "admin",
		Web:            "/admin/storage",
		Screen:         "admin/storage",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "storage",
	},
	{
		Key:            "admin.backup",
		Label:          "备份",
		Board:          "admin",
		Web:            "/admin/backup",
		Screen:         "admin/backup",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "backup",
	},
	{
		Key:            "admin.llm",
		Label:          "LLM",
		Board:          "admin",
		Web:            "/admin/llm",
		Screen:         "admin/llm",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "llm",
	},
	{
		Key:            "admin.api",
		Label:          "开放 API 管理",
		Board:          "admin",
		Web:            "/admin/api",
		Screen:         "admin/api",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}", "POST /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "api",
	},
	{
		Key:            "admin.mail",
		Label:          "邮箱与域名池",
		Board:          "admin",
		Web:            "/admin/mail",
		Screen:         "admin/mail",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "mail",
	},
	{
		Key:            "admin.oauth",
		Label:          "OAuth 应用",
		Board:          "admin",
		Web:            "/admin/oauth",
		Screen:         "admin/oauth",
		Why:            "",
		API:            []string{"GET /api/v1/admin/{section}"},
		Scopes:         []string{"admin:all"},
		OptionalScopes: nil,
		AdminSection:   "oauth",
	},
	{
		Key:            "me.mail",
		Label:          "一次性邮箱",
		Board:          "me",
		Web:            "/mail/burner",
		Screen:         "me/mail",
		Why:            "",
		API:            []string{"GET /api/v1/mail/burners", "POST /api/v1/mail/burners", "DELETE /api/v1/mail/burners/{id}"},
		Scopes:         []string{"mail:burner"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "me.mail.box",
		Label:          "这个箱子收到的信",
		Board:          "me",
		Web:            "",
		Screen:         "me/mail/box",
		Why:            "",
		API:            []string{"GET /api/v1/mail/burners/{id}", "GET /api/v1/mail/burners/{id}/messages", "GET /api/v1/mail/burners/{id}/messages/{message_id}"},
		Scopes:         []string{"mail:burner"},
		OptionalScopes: nil,
		AdminSection:   "",
	},
	{
		Key:            "oauth.consent",
		Label:          "授权确认",
		Board:          "me",
		Web:            "/oauth/authorize",
		Screen:         "",
		Why:            "同意页是 OAuth 唯一的那道人的判断：终端里也能按的话，就成了程序自己批准自己",
		API:            nil,
		Scopes:         nil,
		OptionalScopes: nil,
		AdminSection:   "",
	},
}

// Scopes 是令牌权限的人话说明。登录时的同意提示、以及
// 「你这把令牌看不了这个」那句话都读它。
var Scopes = []Scope{
	{Key: "me:read", Label: "读我自己的资料", Detail: "昵称、积分、等级、称号、收藏夹、草稿箱、关注列表、订单", Danger: 0},
	{Key: "me:write", Label: "改我自己的资料、打卡、收藏", Detail: "改昵称简介技能标签、隐私开关、每日打卡、收藏与关注、存草稿、自荐项目", Danger: 1},
	{Key: "community:read", Label: "读社区里公开的那些", Detail: "成员目录与他人主页、排行榜、项目目录、活动列表、商店橱窗、称号图鉴", Danger: 0},
	{Key: "economy:write", Label: "花我的积分", Detail: "在商店下单、给帖子打赏、发悬赏、用补签卡 —— 都会真的扣掉积分", Danger: 1},
	{Key: "activities:write", Label: "替我报名活动", Detail: "报名、退出、提交作品 —— 有名额和资格判定，和网页上完全一样", Danger: 1},
	{Key: "notifications:read", Label: "读我的通知", Detail: "通知列表与实时推送流 —— 里面带着 @ 我的那条消息的正文", Danger: 1},
	{Key: "notifications:write", Label: "标记已读、改通知偏好", Detail: "把通知标成已读、开关某一类通知。**读不到内容**", Danger: 0},
	{Key: "groups:read", Label: "读我所在的群", Detail: "群列表、成员名册、聊天记录、按天回看、资源库、关键词雷达、群统计 —— 只限你自己在的群", Danger: 1},
	{Key: "forum:read", Label: "读论坛", Detail: "帖子列表、帖子正文和回复 —— 只给你本来就看得到的那些", Danger: 0},
	{Key: "forum:write", Label: "以我的名义发帖和回复", Detail: "发出来的帖子和回复署的是你的名字。版块权限、等级门槛、敏感词、发帖频率限制和网页上完全一样 —— 令牌不是一条绕开规则的近路", Danger: 1},
	{Key: "mail:burner", Label: "开一次性邮箱并读它收到的信", Detail: "只能开一次性邮箱、读这把令牌自己开的那几个箱子。你在网页上开的箱子它看不到，你的自有域名和长期邮箱它也看不到", Danger: 1},
	{Key: "mail:read", Label: "读我所有的邮箱", Detail: "包括自有域名和长期邮箱里的每一封信。邮箱里有验证码和找回密码的链接，所以这一项等于把你在别的网站上的账号一起交出去 —— 默认不给", Danger: 2},
	{Key: "groups:send", Label: "往我所在的群发消息", Detail: "发出来的消息署名是群里那个机器人，不是你。令牌泄漏意味着别人能用机器人的身份在群里说话 —— 这一项默认不给", Danger: 2},
	{Key: "admin:all", Label: "以管理员身份操作后台", Detail: "能调后台接口。具体能做什么仍然由你的身份组决定，一条都不多。但用它做的每一件事，审计日志上署的都是你的名字 —— 这一项默认不给", Danger: 2},
}

// AdminSections 是后台分区的**名字**。
//
// 注意：终端里真正列出哪几个分区**不看这张表**，看
// `GET /api/v1/admin/sections`（那条是按人算过的）。
// 这张表只用来在离线时把 section key 翻译成人话。
var AdminSections = []AdminSection{
	{Key: "dashboard", Label: "仪表盘", Description: "活跃度、系统健康、磁盘水位"},
	{Key: "health", Label: "健康与告警", Description: "坏了的时候，有人会知道吗"},
	{Key: "storage", Label: "存储与裁剪", Description: "空间花在哪，裁掉的还找不找得回来"},
	{Key: "backup", Label: "备份与异地副本", Description: "明天服务器没了，站还回不回得来"},
	{Key: "audit", Label: "审计日志", Description: "谁在什么时候做了什么"},
	{Key: "users", Label: "用户", Description: "封禁、加减分、发身份组、踢下线"},
	{Key: "user", Label: "用户详情", Description: "一个人的全部：积分、身份组、处罚、设备、称号"},
	{Key: "binds", Label: "绑定队列", Description: "谁在等着把微信号和账号连起来"},
	{Key: "roles", Label: "身份组与权限矩阵", Description: "谁能做什么"},
	{Key: "invites", Label: "邀请码", Description: "谁请来的谁"},
	{Key: "reports", Label: "举报队列", Description: "有人举报了什么，处理到哪一步了"},
	{Key: "appeals", Label: "申诉", Description: "被处罚的人说了什么"},
	{Key: "posts", Label: "帖子管理", Description: "批量删帖、移版块、加精"},
	{Key: "escalation", Label: "升级处置", Description: "需要第二个人点头的那些处罚"},
	{Key: "approvals", Label: "审批队列", Description: "需要走审批的后台操作"},
	{Key: "words", Label: "敏感词", Description: "拦什么、怎么拦"},
	{Key: "boards", Label: "版块", Description: "版块、可见性、版主、标签"},
	{Key: "groups", Label: "群与同步", Description: "同步开关、游标、失败的任务"},
	{Key: "points", Label: "积分总览", Description: "发了多少、谁拿得多、每日上限压不压得住"},
	{Key: "points-ledger", Label: "积分流水", Description: "每一笔从哪来、到哪去"},
	{Key: "points-levels", Label: "等级", Description: "几分升一级、每级解锁什么"},
	{Key: "shop", Label: "商店管理", Description: "上架、库存、发货"},
	{Key: "activities", Label: "活动管理", Description: "活动、报名、资格、导出"},
	{Key: "broadcast", Label: "群发", Description: "站长往群里说话的唯一入口"},
	{Key: "community", Label: "社区健康", Description: "新人留没留下、谁在边缘"},
	{Key: "settings", Label: "系统设置", Description: "数值与阈值，改一次留一条历史"},
	{Key: "flags", Label: "功能开关", Description: "整块功能的开关。关掉之后导航消失、页面 404"},
	{Key: "modules", Label: "模块", Description: "可插拔的玩法。关掉之后连后台任务都不跑"},
	{Key: "api", Label: "开放 API 管理", Description: "逐群代发授权、代发日志、SSH 网关令牌"},
	{Key: "llm", Label: "LLM", Description: "配没配、通不通、链接摘要跑到哪了"},
	{Key: "mail", Label: "邮箱与域名池", Description: "域名、箱子、拦下来的信"},
	{Key: "oauth", Label: "OAuth 应用", Description: "谁能拿站里的账号去登录别的地方"},
}
